"""initial schema: budget + snipe

Revision ID: a6d41f18e183
Revises: 
Create Date: 2026-06-25 19:24:56.605475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import quartermaster.db


# revision identifiers, used by Alembic.
revision: str = 'a6d41f18e183'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cap_cents', sa.Integer(), nullable=False),
    sa.Column('committed_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('cap_cents >= 0', name='ck_budget_cap_nonneg'),
    sa.CheckConstraint('committed_cents <= cap_cents', name='ck_budget_committed_le_cap'),
    sa.CheckConstraint('committed_cents >= 0', name='ck_budget_committed_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('snapshot_hash', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('EBAY_API', 'CLASSIFIEDS_EMAIL', name='source'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'REGISTERED', 'VERIFIED', 'FIRED', 'WON', 'PAID', 'SHIPPED', 'RECEIVED', 'TESTED', 'KEPT', 'RETURNED', 'LOST', 'EXPIRED', 'CANCELLED', 'ERROR', 'NEEDS_HUMAN_RECONCILE', name='state'), nullable=False),
    sa.Column('reserved_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', quartermaster.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', quartermaster.db.UTCDateTime(), nullable=False),
    sa.CheckConstraint('reserved_cents >= 0', name='ck_snipe_reserved_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'ebay_item_id', 'snapshot_hash', name='uq_snipe_idem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snipe')
    op.drop_table('budget')
    # ### end Alembic commands ###
